@startuml

scale 2
left to right direction


skinparam Shadowing true


skinparam actor {
BorderColor black
FontName Courier
        BackgroundColor Gold
}

skinparam usecase {
BackgroundColor DarkSeaGreen
BorderColor DarkSlateGray

BackgroundColor YellowGreen
BorderColor YellowGreen

ArrowColor Olive
}
actor Administrator

package Domain {
  usecase "Define business rules" as Define
  usecase "Define Aggregates" as Aggregates
  usecase "Define Entities" as Entities
  usecase "Define Value Objects" as ValueObjects
}

package Application {
  usecase "Define Services" as Services
  usecase "Define Commands" as Commands
  usecase "Define Queries" as Queries
}

package Infrastructure {
  usecase "Define Repositories" as Repositories
  usecase "Define Data Access Objects" as DataAccessObjects
  usecase "Define External Services" as ExternalServices
}

User --> Services
Administrator --> Services

Services --> Commands
Services --> Queries

Commands --> Aggregates
Commands --> Entities
Commands --> ValueObjects

Queries --> Aggregates
Queries --> Entities
Queries --> ValueObjects

Aggregates --> Define
Entities --> Define
ValueObjects --> Define

Repositories --> DataAccessObjects
ExternalServices --> DataAccessObjects

DataAccessObjects --> Services

@enduml
